//
//  ShowGifInteractor.swift
//  GiphyApp
//
//  Created by asylzhan on 11/4/17.
//  Copyright (c) 2017 asylzhan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowGifBusinessLogic {
    func doSomething(request: ShowGif.Something.Request)
}

protocol ShowGifDataStore {
    //var name: String { get set }
}

class ShowGifInteractor: ShowGifBusinessLogic, ShowGifDataStore {
    var presenter: ShowGifPresentationLogic?
    var worker: ShowGifWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ShowGif.Something.Request) {
        worker = ShowGifWorker()
        worker?.doSomeWork()
        
        let response = ShowGif.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
