//
//  ShowGifPresenter.swift
//  GiphyApp
//
//  Created by asylzhan on 11/4/17.
//  Copyright (c) 2017 asylzhan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowGifPresentationLogic {
    func presentSomething(response: ShowGif.Something.Response)
}

class ShowGifPresenter: ShowGifPresentationLogic {
    weak var viewController: ShowGifDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ShowGif.Something.Response) {
        let viewModel = ShowGif.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
