//
//  ShowGifInteractor.swift
//  GiphyApp
//
//  Created by asylzhan on 11/4/17.
//  Copyright (c) 2017 asylzhan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FLAnimatedImage

protocol ShowGifBusinessLogic {
    func getGif(request: ShowGif.GetGif.Request)
}

protocol ShowGifDataStore {
    var gif: Gif! { get set }
}

class ShowGifInteractor: ShowGifBusinessLogic, ShowGifDataStore {
    var presenter: ShowGifPresentationLogic?
    var worker: ShowGifWorker?
    
    var gif: Gif!
    //var name: String = ""
    
    // MARK: Do something
    
    func getGif(request: ShowGif.GetGif.Request) {
        worker = ShowGifWorker()
        worker?.doSomeWork()
        
        let response = ShowGif.GetGif.Response(gif: gif)
        presenter?.presentGif(response: response)
    }
}
