//
//  ShowGifViewController.swift
//  GiphyApp
//
//  Created by asylzhan on 11/4/17.
//  Copyright (c) 2017 asylzhan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FLAnimatedImage

protocol ShowGifDisplayLogic: class {
    func displayGif(viewModel: ShowGif.GetGif.ViewModel)
}

class ShowGifViewController: UIViewController, ShowGifDisplayLogic {
    var interactor: ShowGifBusinessLogic?
    var router: (NSObjectProtocol & ShowGifRoutingLogic & ShowGifDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ShowGifInteractor()
        let presenter = ShowGifPresenter()
        let router = ShowGifRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: Outlet property
    
    @IBOutlet weak var gifImageView: GIFAnimateImageView!
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        getGif()
    }
    
    // MARK: Do something
        
    func getGif() {
        let request = ShowGif.GetGif.Request()
        interactor?.getGif(request: request)
    }
    
    func displayGif(viewModel: ShowGif.GetGif.ViewModel) {
        let url = viewModel.displayedGif.gif.url
        gifImageView.loadImage(url)
    }
}
