//
//  ListGifsModels.swift
//  GiphyApp
//
//  Created by asylzhan on 11/4/17.
//  Copyright (c) 2017 asylzhan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FLAnimatedImage


enum ListGifs {
    
    // MARK: API data models
    
    enum FetchGifs {
        struct Request {
            var phrase: String
            var urls: [String]
            
            init(phrase: String = "", urls: [String] = [""]) {
                self.phrase = phrase
                self.urls = urls
            }
        }
        struct Response {
            var gifs: [Gif]
        }
        struct ViewModel {
            struct DisplayedGif {
                let id: String
                let url: String
            }
            var displayedGifs: [DisplayedGif]
        }
    }
    
    // MARK: Persistent data models
    
    enum FetchManagedGifs {
        struct Request {}
        struct Response {
            var gifImages: [Data]
        }
        struct ViewModel {
            struct DisplayedAnimatedImage {
                let gifImage: Data
            }
            var displayedGifImages: [DisplayedAnimatedImage]
            
        }
    }
}
