//
//  ListGifsPresenter.swift
//  GiphyApp
//
//  Created by asylzhan on 11/4/17.
//  Copyright (c) 2017 asylzhan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListGifsPresentationLogic {
    func presentSomething(response: ListGifs.FetchGifs.Response)
}

class ListGifsPresenter: ListGifsPresentationLogic {
    weak var viewController: ListGifsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ListGifs.FetchGifs.Response) {
        let viewModel = ListGifs.FetchGifs.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
