//
//  ListGifsInteractor.swift
//  GiphyApp
//
//  Created by asylzhan on 11/4/17.
//  Copyright (c) 2017 asylzhan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FLAnimatedImage

protocol ListGifsBusinessLogic {
    func searchGif(request: ListGifs.FetchGifs.Request)
    func fetchAllManagedGifs(request: ListGifs.FetchManagedGifs.Request)
}

protocol ListGifsDataStore {
    var gifs: [Gif]? { get }
    var gifData: [Data]? { get }
}

class ListGifsInteractor: ListGifsBusinessLogic, ListGifsDataStore {
    var presenter: ListGifsPresentationLogic?
    var worker: ListGifsWorker?
    var coreDataWorker: GifCoreDataWorker?
    var gifs: [Gif]?
    var gifData: [Data]?
    
    /// Searches by phrase gets corresponding gifs
    ///
    /// - request: List Gif Model Request
    
    func searchGif(request: ListGifs.FetchGifs.Request) {
        worker = ListGifsWorker()
        
        worker?.searchGif(phrase: request.phrase, completion: { gifs, error in
            self.gifs = gifs
            let response = ListGifs.FetchGifs.Response(gifs: gifs)
            self.presenter?.presentFetchedGifs(response: response)
        })
    }
    
    func fetchAllManagedGifs(request: ListGifs.FetchManagedGifs.Request) {
        coreDataWorker = GifCoreDataWorker()
        
        coreDataWorker?.allGifLists(completion: { data in
            self.gifData = data
            let response = ListGifs.FetchManagedGifs.Response(gifImages: data)
            self.presenter?.presentFetchedManagedGifs(response: response)
        })
        
    }
}
