//
//  ListGifsRouter.swift
//  GiphyApp
//
//  Created by asylzhan on 11/4/17.
//  Copyright (c) 2017 asylzhan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListGifsRoutingLogic {
    func routeToShowGif(segue: UIStoryboardSegue?)
}

protocol ListGifsDataPassing {
    var dataStore: ListGifsDataStore? { get }
}

class ListGifsRouter: NSObject, ListGifsRoutingLogic, ListGifsDataPassing {
    weak var viewController: ListGifsViewController?
    var dataStore: ListGifsDataStore?
    
    // MARK: Routing
    
    func routeToShowGif(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowGifViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowGif(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowGifViewController") as! ShowGifViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowGif(source: dataStore!, destination: &destinationDS)
            navigateToShowGif(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToShowGif(source: ListGifsViewController, destination: ShowGifViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToShowGif(source: ListGifsDataStore, destination: inout ShowGifDataStore)
    {
        let selected = viewController?.collectionView?.indexPathsForSelectedItems?.first?.row
//        print("Selected gif \(selected) Data: \(source.gifs)")
        destination.gif = source.gifs![selected!]
    }
}
